<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Core\Routing\TrustedRedirectResponse;

/**
 * Implement hook_form_alter.
 */
function learning_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ( $form_id === 'node_article_form' ) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'form_article_submit';
      }
    }
  }
}

/**
 * Submit handler for article node.
 */
function form_article_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $url = Url::fromUri('internal:/works/page');
  $form_state->setRedirectUrl($url);
}

/**
 * Implements hook_theme().
 */
function learning_module_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => [
        'demo_blok' => NULL
      ],
    ],
  ];
}
?>